### ISSUE TITLE
Returned to game and all items turned vanilla

### ISSUE THREAD

**Issue by jooniejoone** [dplochcoder/HollowKnight.UnRando#1]
I started an unrando seed.  It was going well, but I couldn't finish it before I had to leave.  When I came back to the game later and resumed the seed, the item sequence was completely gone, and it seemed like all of the items turned vanilla.

**Comment by dplochcoder** [comment]
Fixed by https://github.com/dplochcoder/HollowKnight.UnRando/commit/dea477b944edd80a58596f4d3c654f55dbb08728
